/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as CampeonatosRouteImport } from './routes/campeonatos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ContasRouteImport } from './routes/contas'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as FrequenciaRouteImport } from './routes/frequencia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as MensalidadesRouteImport } from './routes/mensalidades'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as ProfessoresRouteImport } from './routes/professores'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as TurmasRouteImport } from './routes/turmas'
import { Route as VideoRouteImport } from './routes/video'
import { Route as ApiBillingWebhookRouteImport } from './routes/api/billing-webhook'
import { Route as ApiEntrarRouteImport } from './routes/api/entrar'
import { Route as ApiWaBotRouteImport } from './routes/api/wa-bot'
import { Route as ApiWaCredsRouteImport } from './routes/api/wa-creds'
import { Route as ApiWhatsappRouteImport } from './routes/api/whatsapp'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const CampeonatosRoute = CampeonatosRouteImport.update({
  id: '/campeonatos',
  path: '/campeonatos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContasRoute = ContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const FrequenciaRoute = FrequenciaRouteImport.update({
  id: '/frequencia',
  path: '/frequencia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const MensalidadesRoute = MensalidadesRouteImport.update({
  id: '/mensalidades',
  path: '/mensalidades',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessoresRoute = ProfessoresRouteImport.update({
  id: '/professores',
  path: '/professores',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasRoute = TurmasRouteImport.update({
  id: '/turmas',
  path: '/turmas',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing-webhook',
  path: '/api/billing-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEntrarRoute = ApiEntrarRouteImport.update({
  id: '/api/entrar',
  path: '/api/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaBotRoute = ApiWaBotRouteImport.update({
  id: '/api/wa-bot',
  path: '/api/wa-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaCredsRoute = ApiWaCredsRouteImport.update({
  id: '/api/wa-creds',
  path: '/api/wa-creds',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappRoute = ApiWhatsappRouteImport.update({
  id: '/api/whatsapp',
  path: '/api/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alunos': typeof AlunosRoute
  '/assinatura': typeof AssinaturaRoute
  '/campeonatos': typeof CampeonatosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/empresa': typeof EmpresaRoute
  '/estoque': typeof EstoqueRoute
  '/frequencia': typeof FrequenciaRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/mensalidades': typeof MensalidadesRoute
  '/planos': typeof PlanosRoute
  '/professores': typeof ProfessoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/turmas': typeof TurmasRoute
  '/video': typeof VideoRoute
  '/api/billing-webhook': typeof ApiBillingWebhookRoute
  '/api/entrar': typeof ApiEntrarRoute
  '/api/wa-bot': typeof ApiWaBotRoute
  '/api/wa-creds': typeof ApiWaCredsRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alunos': typeof AlunosRoute
  '/assinatura': typeof AssinaturaRoute
  '/campeonatos': typeof CampeonatosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/empresa': typeof EmpresaRoute
  '/estoque': typeof EstoqueRoute
  '/frequencia': typeof FrequenciaRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/mensalidades': typeof MensalidadesRoute
  '/planos': typeof PlanosRoute
  '/professores': typeof ProfessoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/turmas': typeof TurmasRoute
  '/video': typeof VideoRoute
  '/api/billing-webhook': typeof ApiBillingWebhookRoute
  '/api/entrar': typeof ApiEntrarRoute
  '/api/wa-bot': typeof ApiWaBotRoute
  '/api/wa-creds': typeof ApiWaCredsRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/alunos': typeof AlunosRoute
  '/assinatura': typeof AssinaturaRoute
  '/campeonatos': typeof CampeonatosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contas': typeof ContasRoute
  '/empresa': typeof EmpresaRoute
  '/estoque': typeof EstoqueRoute
  '/frequencia': typeof FrequenciaRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/mensalidades': typeof MensalidadesRoute
  '/planos': typeof PlanosRoute
  '/professores': typeof ProfessoresRoute
  '/relatorios': typeof RelatoriosRoute
  '/turmas': typeof TurmasRoute
  '/video': typeof VideoRoute
  '/api/billing-webhook': typeof ApiBillingWebhookRoute
  '/api/entrar': typeof ApiEntrarRoute
  '/api/wa-bot': typeof ApiWaBotRoute
  '/api/wa-creds': typeof ApiWaCredsRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/alunos'
    | '/assinatura'
    | '/campeonatos'
    | '/configuracoes'
    | '/contas'
    | '/empresa'
    | '/estoque'
    | '/frequencia'
    | '/login'
    | '/loja'
    | '/mensalidades'
    | '/planos'
    | '/professores'
    | '/relatorios'
    | '/turmas'
    | '/video'
    | '/api/billing-webhook'
    | '/api/entrar'
    | '/api/wa-bot'
    | '/api/wa-creds'
    | '/api/whatsapp'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/alunos'
    | '/assinatura'
    | '/campeonatos'
    | '/configuracoes'
    | '/contas'
    | '/empresa'
    | '/estoque'
    | '/frequencia'
    | '/login'
    | '/loja'
    | '/mensalidades'
    | '/planos'
    | '/professores'
    | '/relatorios'
    | '/turmas'
    | '/video'
    | '/api/billing-webhook'
    | '/api/entrar'
    | '/api/wa-bot'
    | '/api/wa-creds'
    | '/api/whatsapp'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/alunos'
    | '/assinatura'
    | '/campeonatos'
    | '/configuracoes'
    | '/contas'
    | '/empresa'
    | '/estoque'
    | '/frequencia'
    | '/login'
    | '/loja'
    | '/mensalidades'
    | '/planos'
    | '/professores'
    | '/relatorios'
    | '/turmas'
    | '/video'
    | '/api/billing-webhook'
    | '/api/entrar'
    | '/api/wa-bot'
    | '/api/wa-creds'
    | '/api/whatsapp'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AlunosRoute: typeof AlunosRoute
  AssinaturaRoute: typeof AssinaturaRoute
  CampeonatosRoute: typeof CampeonatosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContasRoute: typeof ContasRoute
  EmpresaRoute: typeof EmpresaRoute
  EstoqueRoute: typeof EstoqueRoute
  FrequenciaRoute: typeof FrequenciaRoute
  LoginRoute: typeof LoginRoute
  LojaRoute: typeof LojaRoute
  MensalidadesRoute: typeof MensalidadesRoute
  PlanosRoute: typeof PlanosRoute
  ProfessoresRoute: typeof ProfessoresRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TurmasRoute: typeof TurmasRoute
  VideoRoute: typeof VideoRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiEntrarRoute: typeof ApiEntrarRoute
  ApiWaBotRoute: typeof ApiWaBotRoute
  ApiWaCredsRoute: typeof ApiWaCredsRoute
  ApiWhatsappRoute: typeof ApiWhatsappRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campeonatos': {
      id: '/campeonatos'
      path: '/campeonatos'
      fullPath: '/campeonatos'
      preLoaderRoute: typeof CampeonatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contas': {
      id: '/contas'
      path: '/contas'
      fullPath: '/contas'
      preLoaderRoute: typeof ContasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frequencia': {
      id: '/frequencia'
      path: '/frequencia'
      fullPath: '/frequencia'
      preLoaderRoute: typeof FrequenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensalidades': {
      id: '/mensalidades'
      path: '/mensalidades'
      fullPath: '/mensalidades'
      preLoaderRoute: typeof MensalidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professores': {
      id: '/professores'
      path: '/professores'
      fullPath: '/professores'
      preLoaderRoute: typeof ProfessoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas': {
      id: '/turmas'
      path: '/turmas'
      fullPath: '/turmas'
      preLoaderRoute: typeof TurmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing-webhook': {
      id: '/api/billing-webhook'
      path: '/api/billing-webhook'
      fullPath: '/api/billing-webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/entrar': {
      id: '/api/entrar'
      path: '/api/entrar'
      fullPath: '/api/entrar'
      preLoaderRoute: typeof ApiEntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-bot': {
      id: '/api/wa-bot'
      path: '/api/wa-bot'
      fullPath: '/api/wa-bot'
      preLoaderRoute: typeof ApiWaBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wa-creds': {
      id: '/api/wa-creds'
      path: '/api/wa-creds'
      fullPath: '/api/wa-creds'
      preLoaderRoute: typeof ApiWaCredsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp': {
      id: '/api/whatsapp'
      path: '/api/whatsapp'
      fullPath: '/api/whatsapp'
      preLoaderRoute: typeof ApiWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AlunosRoute: AlunosRoute,
  AssinaturaRoute: AssinaturaRoute,
  CampeonatosRoute: CampeonatosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContasRoute: ContasRoute,
  EmpresaRoute: EmpresaRoute,
  EstoqueRoute: EstoqueRoute,
  FrequenciaRoute: FrequenciaRoute,
  LoginRoute: LoginRoute,
  LojaRoute: LojaRoute,
  MensalidadesRoute: MensalidadesRoute,
  PlanosRoute: PlanosRoute,
  ProfessoresRoute: ProfessoresRoute,
  RelatoriosRoute: RelatoriosRoute,
  TurmasRoute: TurmasRoute,
  VideoRoute: VideoRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiEntrarRoute: ApiEntrarRoute,
  ApiWaBotRoute: ApiWaBotRoute,
  ApiWaCredsRoute: ApiWaCredsRoute,
  ApiWhatsappRoute: ApiWhatsappRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
